version: "3.9"
services:
  db:
    image: mariadb
    volumes:
      - ./export.sql:/docker-entrypoint-initdb.d/export.sql
    environment:
      MYSQL_DATABASE: swt_crp
      MYSQL_USER: user
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MYSQL_PASSWORD: password
  db-admin:
    image: adminer:latest
    ports:
      - 8080:8080
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80